# Generated by Django 4.1.3 on 2022-11-13 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания конфига'),
        ),
        migrations.AlterField(
            model_name='config',
            name='last_called',
            field=models.DateTimeField(blank=True, verbose_name='время последнего запроса конфига'),
        ),
        migrations.AlterField(
            model_name='config',
            name='service',
            field=models.CharField(max_length=200, unique=True, verbose_name='сервис конфига'),
        ),
        migrations.AlterField(
            model_name='config',
            name='updated_at',
            field=models.DateTimeField(blank=True, verbose_name='дата обновления конфига'),
        ),
    ]
