# Generated by Django 4.1.3 on 2022-11-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_alter_config_created_at_alter_config_last_called_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='last_called',
        ),
        migrations.RemoveField(
            model_name='config',
            name='retention_policy',
        ),
        migrations.AlterField(
            model_name='config',
            name='service',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='сервис конфига'),
        ),
    ]
