# Generated by Django 4.1.3 on 2022-11-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_alter_config_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='service',
            field=models.CharField(blank=True, max_length=200, verbose_name='сервис конфига'),
        ),
        migrations.AlterField(
            model_name='config',
            name='version',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='версия конфига'),
        ),
    ]
