# Generated by Django 4.1.3 on 2022-11-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_alter_config_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='version',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, verbose_name='версия конфига'),
        ),
    ]
