# Generated by Django 4.1.3 on 2022-11-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200, verbose_name='сервис конфига')),
                ('data', models.JSONField(verbose_name='содержимое конфига')),
                ('version', models.IntegerField(verbose_name='версия конфига')),
                ('retention_policy', models.DurationField(verbose_name='интервал жизни конфига')),
                ('last_called', models.DateTimeField(verbose_name='время последнего запроса конфига')),
                ('created_at', models.DateTimeField(verbose_name='дата создания конфига')),
                ('updated_at', models.DateTimeField(verbose_name='дата обновления конфига')),
            ],
        ),
    ]
