# Generated by Django 4.1.3 on 2022-11-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_config_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='version',
            field=models.FloatField(verbose_name='версия конфига'),
        ),
    ]
