# Generated by Django 4.1.3 on 2022-11-15 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_alter_config_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='дата создания конфига'),
        ),
        migrations.AlterField(
            model_name='config',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='дата обновления конфига'),
        ),
    ]
